# Generated by Django 3.0.8 on 2020-08-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='active',
        ),
    ]
