# Generated by Django 3.0.8 on 2020-08-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='userWatchlist', to='auctions.AuctionListing'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
